### ISSUE TITLE
Apache License

### ISSUE THREAD

**Issue by akrzos** [grinapo/collectd-ceph#21]
Are you willing to re-license this code under Apache License so it can be used with OpenStack?

**Comment by y4ns0l0** [comment]
@grinapo What is your opinion ?

**Comment by grinapo** [comment]
I am not in the position to do that. I am the author of my own changes, and I gladly release them under whatever licence you want. 

All the other code (99% of the project) is under GPLv2 by @rochaporto, and he's the only person having the power to relicense it; possibly not even him, since it would need the affirmation of **every** contributor ever in the history of the package. 

Welcome to the Copyright Hell™.

**Comment by grinapo** [comment]
Nothing cen be done here, really.
